# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [1]:
# импорт библиотек
import numpy as np

In [55]:
### YOUR CODE HERE
A_phone = np.array([[1,2,3], [4,5,6], [7,8,9]]) # создаю матрицу 3*3
A_one = np.eye(3) # создаю единичную матрицу
V = np.array([1,2,3])
A_sum = A_one + A_phone # складываю матрицы
A_mul = A_sum@V # умножаю матрицу на вектор
A_t = np.transpose(A_sum)
A_t # транспонирую матрицу
A_inv = np.linalg.inv(A_t) # вычисляю матрицу, обратную транспонированной
print(f"A_sum:\n{A_sum}\nA_mul:\n{A_mul}\nA_t:\n{A_t}\nA_inv:\n{A_inv}") #вывожу пезультаты

A_sum:
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
A_mul:
[15. 34. 53.]
A_t:
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]
A_inv:
[[-6.  -1.   5. ]
 [-2.   0.5  1. ]
 [ 3.   0.  -2. ]]


## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [59]:
### YOUR CODE HERE
m = np.array([[2, 2],[1, 3]])
res = np.linalg.eig(m)
res

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [ ]:
### YOUR CODE HERE
det = 0
while det !=1:
    a = np.random.randint(-10,10,(3,3))
    det = np.linalg.det(a)
print(a)